Linkedin posting
Vaibhavpratapsingh22/Courses pull request #100
Opened 2020-10-04 07:52 UTC by Vaibhavpratapsingh22

Chapter- 4 created 👍

2020-10-04 16:19 UTC, udeysingh95 requested changes
Overall work is very good on this PR - just some minor changes?

2020-10-04 16:19 UTC, udeysingh95 commented on 11-linkedin/4-posting.md
> +### What To Do Before You Post Your Comment On LinkedIn
Why is everything capitalized in this title?

2020-10-05 09:56 UTC, SaarthakDeshmukh approved these changes
The content of this PR is really good. It will be helpful to many. Great Work! @Vaibhavpratapsingh22

2020-10-05 20:09 UTC, udeysingh95 approved these changes

2020-10-06 09:19 UTC, merged