Introduction ⭐
Vaibhavpratapsingh22/Courses pull request #120
Opened 2021-07-09 18:08 UTC by Vaibhavpratapsingh22

Covered the basic introduction to Boostrap framework in a simple and easy-to-understand language.

2021-07-10 06:56 UTC, udeysingh95 commented on C-09-bootstrap/01-introduction.md
> +### "Bootstrap is a free, open-source front-end library for designing websites and web applications. It contains HTML- and CSS-based design templates for everything from typography, forms, buttons, n
why is it written like a header?

2021-07-10 06:56 UTC, udeysingh95 commented on C-09-bootstrap/01-introduction.md
> +## How Bootstrap was started?
this section is giving a lot of extra information. Either make it interesting to read or skip this section in all.

2021-07-10 07:01 UTC, udeysingh95 requested changes

2021-07-10 07:01 UTC, udeysingh95 commented on C-09-bootstrap/01-introduction.md
> +In this chapter we have seen introduction to bootstrap and I hope that you all have tried the starter template to see how it works. In the next chapter we will learn about content system of bootstrap
work on the wording here. Also, you are expecting others to have tried something already when you have only mentioned the include the bootstrap. I like the topic and also, I don't know it - so, I can review these PRs as your student aiming to learn bootstrap.
From this chapter, I only learned theory about the bootstrap, to be honest, no application and I can not directly use it as well.

2021-07-10 12:11 UTC, Vaibhavpratapsingh22 commented on C-09-bootstrap/01-introduction.md
> +```
@udeysingh95, these have to like this as if I make them in different lines then when anyone will copy this code they have to reformat it again to make it in a single line. There is a button for copy that will copy the entire code in one-go.

2021-07-10 12:14 UTC, Vaibhavpratapsingh22 commented on C-09-bootstrap/01-introduction.md
> +In this chapter we have seen introduction to bootstrap and I hope that you all have tried the starter template to see how it works. In the next chapter we will learn about content system of bootstrap
@udeysingh95, in this repo we are just going to understand the Bootstrap theory, the practical part will be done in the second repo. Please check this out by [clicking here](https://github.com/Vaibhavpratapsingh22/website)

2021-07-19 19:16 UTC, udeysingh95 approved these changes

2021-07-20 02:58 UTC, merged