Chapter 2 -  Scrum Master
Vaibhavpratapsingh22/Courses pull request #51
Opened 2020-08-21 13:45 UTC by SaarthakDeshmukh

The second chapter has been created successfully.

2020-08-24 10:04 UTC, haithem1717 commented on 7-scrum-master-role/1-scrum.md
> +### 5. Backlog Refinement
Maybe I have a confusion here,  I thought the backlog  refinement is not a time-boxed event and that it's planned whenever needed.

2020-08-24 10:09 UTC, haithem1717 commented on 7-scrum-master-role/2-scrum-master.md
> +## Scrum Master Responsibility
I feel like this could be elaborated more based on each party involved in the SM's work(Dev team, PO, Organisation).

2020-08-24 10:10 UTC, haithem1717 approved these changes

2020-08-24 10:17 UTC, SaarthakDeshmukh commented on 7-scrum-master-role/1-scrum.md
> +### 5. Backlog Refinement
Hey, @haithem1717 All the events in Scrum are time-boxed. Backlog Refinement needs to be done before the Sprint Planning so that it gives the team a chance to reflect on the backlog items discussed in the meeting before committing to the sprint backlog and sprint goal.

2020-08-24 10:33 UTC, SaarthakDeshmukh commented on 7-scrum-master-role/2-scrum-master.md
> +## Scrum Master Responsibility
I think I have elaborated SM's work towards (PO, Dev Team, and Org) in 2 Topics - 1. Roles of a Scrum Master and 2. Scrum Master Focus Area. Can you check them once? If you still don't get the idea then maybe I will add more content on them. :art:

2020-08-25 04:45 UTC, Vaibhavpratapsingh22 requested changes

2020-08-25 04:45 UTC, Vaibhavpratapsingh22 commented on 7-scrum-master-role/2-scrum-master.md
> +### Team Coaching
Can we change"Team Coaching" to "1. Team Coaching" and "System Coaching" to "2. System Coaching".

2020-08-25 06:08 UTC, udeysingh95 commented on 7-scrum-master-role/1-scrum.md
> +### 5. Backlog Refinement
I agree with Saarthak here. Time-boxing is the heart of Scrum. Otherwise, meetings will just go on forever. As Backlog refinement is not yet recognized as a ceremony by Scrum Community - it is mentioned not to spend more than 10% of sprint time on this event.

2020-08-25 06:09 UTC, udeysingh95 commented on 7-scrum-master-role/2-scrum-master.md
> +## Scrum Master Responsibility
@haithem1717 yes, it has been well explained in the following sections.

2020-08-26 13:26 UTC, udeysingh95 reviewed
Let's wait for some more time till we get our hands on Metrics. I have one cool framework that can support you to learn how to talk in metrics language. we can discuss that framework in the next week - if things didn't move till then.

2020-08-28 15:28 UTC, udeysingh95 commented
Let's talk about metric shortly in this chapter and leave the topic for challenge task. There we can learn and apply it in detail.
In that case, some updates on this PR and we can move forward to merge it. @SaarthakDeshmukh

2020-08-28 15:50 UTC, udeysingh95 approved these changes

2020-08-28 16:20 UTC, Vaibhavpratapsingh22 approved these changes
## Good work 🚀
Finally, we are merging it.

2020-08-28 16:21 UTC, merged