Chapter 3 -  Facilitation
Vaibhavpratapsingh22/Courses pull request #52
Opened 2020-08-23 14:13 UTC by SaarthakDeshmukh

Done with the facilitation chapter.😁😀:sparkles:

2020-08-23 16:47 UTC, udeysingh95 reviewed
The overall content quality is very high but its too much information to process in one read. Try to make it easy for reader to read. 
Keep up the quality though.

2020-08-23 16:47 UTC, udeysingh95 commented on 7-scrum-master-role/3-facilitation.md
> +The definition of facilitate is "to make easy" or "ease a process." Facilitation is the art of leading people through processes towards agreed-upon objectives in a manner that encourages participatio
"to make easy" or "ease a process" - not so directly pointing towards facilitation - what do you think about facilitation - how would you describe it in a word or a sentence. I am more interested in hearing your definition of Facilitation.

2020-08-23 16:47 UTC, udeysingh95 commented on 7-scrum-master-role/3-facilitation.md
> +## Who is a Facilitator?
I would be more interested to read first about - what is facilitation and why it is required?!  
Then we can move on to this topic.

2020-08-23 16:47 UTC, udeysingh95 commented on 7-scrum-master-role/3-facilitation.md
> +Facilitation is both an art and a science. The science comes from what we know about how people think, how groups behave and teams develop. The art is how the facilitator learns to dance in the momen
This is important section - maybe lets start from here.

2020-08-23 16:47 UTC, udeysingh95 commented on 7-scrum-master-role/3-facilitation.md
> +1. The facilitator leads discussion but does not dominate.
There is a lot of information in here and in the para below - but it is not readable - can we make it more easy to read? 
Maybe some wordings improvements - some English corrections and use of easy words as well as - removing redundant items like "The Facilitator is...".

2020-08-23 16:47 UTC, udeysingh95 commented on 7-scrum-master-role/README.md
> +Now we are going to discuss one of the stances that the Scrum Master need to master, that is the facilitation stance. This chapter deals with some topics like, what is a facilitator, how to facilitat
```suggestion
Now we are going to discuss one of the stances that the Scrum Master need to master, that is the **Facilitator** stance. This chapter deals with some topics like, what is a facilitator, how to facilitate the event and how to be a high-quality facilitator and the Science of Facilitation.
```

2020-08-23 16:47 UTC, udeysingh95 commented on 7-scrum-master-role/3-facilitation.md
> +<p align="center"> <img width="" height="" src="https://scrumorg-website-prod.s3.amazonaws.com/drupal/inline-images/A58BD878-E8B0-4EFA-99E8-D2A3C5DD3CC4%203.png"></p>
This is super image - but i didn't get what is it doing here?

2020-08-23 21:14 UTC, SaarthakDeshmukh commented on 7-scrum-master-role/3-facilitation.md
> +<p align="center"> <img width="" height="" src="https://scrumorg-website-prod.s3.amazonaws.com/drupal/inline-images/A58BD878-E8B0-4EFA-99E8-D2A3C5DD3CC4%203.png"></p>
I thought maybe an image will increase user attraction. Should I add another one?

2020-08-24 08:09 UTC, udeysingh95 commented on 7-scrum-master-role/3-facilitation.md
> +<p align="center"> <img width="" height="" src="https://scrumorg-website-prod.s3.amazonaws.com/drupal/inline-images/A58BD878-E8B0-4EFA-99E8-D2A3C5DD3CC4%203.png"></p>
Yes, but it should have some meaning as well - directed towards the topic!

2020-08-24 08:59 UTC, Vaibhavpratapsingh22 requested changes

2020-08-24 08:59 UTC, Vaibhavpratapsingh22 commented on 7-scrum-master-role/3-facilitation.md
> +**Facilitation requires an understanding of the following:**
Can we give this heading Level-3 and make the sub-points at Level-4.

2020-08-24 08:59 UTC, Vaibhavpratapsingh22 commented on 7-scrum-master-role/3-facilitation.md
> +1. **The input**: Effective facilitation requires knowing the input.
Same for here and the below topic. After level-2 we cant jump directly to level-4.

2020-08-24 08:59 UTC, Vaibhavpratapsingh22 commented on 7-scrum-master-role/3-facilitation.md
> +- Over prepare: Make sure you know the meeting topics backward and forwards. Anticipate questions that the team or other meeting participants may ask you. Imagine you’re preparing for a big political
Mark these points with numbers to maintain the consistency.

2020-08-24 09:04 UTC, SaarthakDeshmukh commented on 7-scrum-master-role/3-facilitation.md
> +**Facilitation requires an understanding of the following:**
I have changed the heading to level-3 but I think we should let the points be points, as it is not a heading. That's what I feel.

2020-08-24 09:06 UTC, SaarthakDeshmukh commented on 7-scrum-master-role/3-facilitation.md
> +1. **The input**: Effective facilitation requires knowing the input.
I am a bit confused here, as these are just internal points and not heading. What should be done here? @udeysingh95

2020-08-24 09:07 UTC, SaarthakDeshmukh commented on 7-scrum-master-role/3-facilitation.md
> +- Over prepare: Make sure you know the meeting topics backward and forwards. Anticipate questions that the team or other meeting participants may ask you. Imagine you’re preparing for a big political
Done

2020-08-24 09:15 UTC, Vaibhavpratapsingh22 requested changes

2020-08-24 09:15 UTC, Vaibhavpratapsingh22 commented on 7-scrum-master-role/3-facilitation.md
> +**Facilitation requires an understanding of the following:**
But we have to follow the Structure. You can make heading for Level-3 in your words that's the only solution.

2020-08-24 09:19 UTC, SaarthakDeshmukh commented on 7-scrum-master-role/3-facilitation.md
> +1. **The input**: Effective facilitation requires knowing the input.
@Vaibhavpratapsingh22 I have changed the fonts from bold to italics as they are just internal points. What do you say?

2020-08-24 09:47 UTC, Vaibhavpratapsingh22 commented on 7-scrum-master-role/3-facilitation.md
> +1. **The input**: Effective facilitation requires knowing the input.
Commit the changes then I will check.

2020-08-24 09:57 UTC, Vaibhavpratapsingh22 requested changes

2020-08-24 09:57 UTC, Vaibhavpratapsingh22 commented on 7-scrum-master-role/3-facilitation.md
> +### 1. The input:
Can we remove the colons from level-3 headings?

2020-08-24 09:57 UTC, Vaibhavpratapsingh22 commented on 7-scrum-master-role/3-facilitation.md
> +- **Community** – what are the guiding norms of the community with whom you are facilitating a discussion? Facilitation creates the time and space that honors the voices of individuals as people and
Make it in points and replace "-" with ":".

2020-08-24 09:59 UTC, Vaibhavpratapsingh22 requested changes

2020-08-24 09:59 UTC, Vaibhavpratapsingh22 commented on 7-scrum-master-role/3-facilitation.md
>  This was all about facilitation now to summarize,
This line can be removed.

2020-08-24 10:08 UTC, SaarthakDeshmukh commented on 7-scrum-master-role/3-facilitation.md
> +### 1. The input:
will do that

2020-08-24 15:32 UTC, udeysingh95 requested changes
### Improve Readability 
Some titles are with articles, some are short, and some questions. Try to be more consistent in the direction of Title naming.
The language in the section as well - is inconsistent - some points are in question way and some are statements within one section. It makes it hard to read.

2020-08-24 15:32 UTC, udeysingh95 commented on 7-scrum-master-role/3-facilitation.md
> +### Facilitation requires an understanding of the following:
Is this something that needs to be discussed in so much detail. 
I couldn't get the same amount of value as its size.

2020-08-24 15:32 UTC, udeysingh95 commented on 7-scrum-master-role/3-facilitation.md
> +<p align="center"> <img width="" height="" src="https://www.facilitatingresults.ca/2016/images/facilitation-ottawa.jpg"><p>
I liked the illustration.

2020-08-24 15:32 UTC, udeysingh95 commented on 7-scrum-master-role/3-facilitation.md
> +Outcome of this facilitated event is a high-quality decision that is owned by everyone. What that means is everyone is holding each other accountable for the decision made. This high-quality decision
Very well said.

2020-08-24 15:32 UTC, udeysingh95 commented on 7-scrum-master-role/3-facilitation.md
> +A SM should facilitate by creating a "container" for the team to fill up with their ideas and innovations. The container, often a set of agenda questions or some other lightweight (and flexible) stru
I liked the metaphor here "container" which is empty. Very aptly said.

2020-08-24 15:32 UTC, udeysingh95 commented on 7-scrum-master-role/3-facilitation.md
> +## How can you improve your facilitation skills?
too much information here.

2020-08-24 15:32 UTC, udeysingh95 commented on 7-scrum-master-role/3-facilitation.md
> +<p align="center"> <img width="" height="" src="https://www.trg-inc.com/wp-content/uploads/2019/06/FTP-graphic-facilitation-by-Kat-Haugh-e1565282021774.png"></p>
The picture says a lot already. Try to cut the text part that is being portrayed again here in picture.

2020-08-24 15:32 UTC, udeysingh95 commented on 7-scrum-master-role/3-facilitation.md
> +Facilitation is about creating the space for what’s needed to help people show up as their most naturally creative selves, voice their point of view authentically, hear different perspectives, develo
Start with the elevator pitch of "facilitation". 
catch the reader right here - because at the moment - this is too flat.

2020-08-24 15:32 UTC, udeysingh95 commented on 7-scrum-master-role/3-facilitation.md
> +At the end of the day, facilitation is more of an art than a science. The more you do it, the more sophisticated your skills will become! In many ways, the best facilitation training is being on the
This one and the next one - both are saying the same things - and sounds like they have been taken from two different sources. try to have only one para in Summary - its summary after all and cover all the points from above section.

2020-08-24 15:33 UTC, udeysingh95 commented
@Vaibhavpratapsingh22 very cool review. You learned very fast. Keep it up!

2020-08-25 04:16 UTC, udeysingh95 reviewed
Really good work. 
the content was already very rich in the first iteration. readability has also improved a lot. 
One section could be improved further and then we are good here.

2020-08-25 04:16 UTC, udeysingh95 commented on 7-scrum-master-role/3-facilitation.md
> +### Facilitation requires an understanding of the following:
This section can be further trimmed. Maybe a paragraph which gives an overview of all the important points to be kept in mind while facilitating - Flexibility, Balance, Silence. Maybe you can only talk about what seems to be important for you as a facilitator. Like for me - connection is one of the most important ones and I would start talking in this para with connection only - maybe community is not so important for me at the moment. - because I mostly with the same community and haven't come across a challenge where my words got perceived in a different way due to "community" part of understanding.

2020-08-25 11:37 UTC, Vaibhavpratapsingh22 approved these changes

2020-08-25 11:51 UTC, udeysingh95 approved these changes

2020-08-28 10:19 UTC, merged