Chapter 4 - Team Building
Vaibhavpratapsingh22/Courses pull request #54
Opened 2020-08-25 15:43 UTC by SaarthakDeshmukh

Completed the chapter 4 - team building

2020-08-26 07:35 UTC, udeysingh95 commented
Very precise on the number of lined in the MD file. ;)

2020-08-26 07:47 UTC, Vaibhavpratapsingh22 commented
# Great Work! 💯 
The structure is looking in proper shape 👍

2020-08-26 13:14 UTC, udeysingh95 requested changes

2020-08-26 13:14 UTC, udeysingh95 commented on 7-scrum-master-role/4-team-building.md
> +## Agile Project Kick-Off Meeting
This is a very important topic. 
I would like to see this all presented in your words - at the moment -there are nice topics covered in here which are in flow - but they are giving too much information - which leads to question like do we need this all in the beginning or not? 
Agile Kick-off meeting content is also very good - make it more readable. 
Try to remove everything from that section and tell the whole story in your own words. 
Add some pictures if you could think off - or if some are relatable - images also say a lot and keep the reader engaged. 
I like the quality of content in your PRs but the reading factor always needs work. Look at the MD files in Algorithm folder in this repo - that is super boring topic and the creator has collected information in really interactive and descriptive way. 
I would recommend that kind of approach.

2020-08-26 13:14 UTC, udeysingh95 commented on 7-scrum-master-role/4-team-building.md
> +## Team Building Activities
This is very much in demand these days - Maybe add some more games - with links only - so people can go and read about themselves and you don't have to explain everything in detail - i would like you to cover some more games and also what kind of games are used for what kind of situations, some focus on what games could be played in remote setup. Are all games playable with all kinds of teams - or they also depend on the size, maturity of teams?

2020-08-26 13:14 UTC, udeysingh95 commented on 7-scrum-master-role/4-team-building.md
> +## Making High Performing Teams
This is too much flat text.

2020-08-26 13:14 UTC, udeysingh95 commented on 7-scrum-master-role/4-team-building.md
> +<p align="center"> <img width="600" height="" src="https://blog.infodiagram.com/wp-content/uploads/2018/06/gr_dev_1.jpg"></p>
In the standard Tuckman model - there were only 4 phases of development was introduced - try to look for that and if you find this one more relatable to your beliefs - then i would be interested to read - why so?

2020-08-26 13:14 UTC, udeysingh95 commented on 7-scrum-master-role/4-team-building.md
> +<p align="center"> <img width="700" height="" src="https://storage.ning.com/topology/rest/1.0/file/get/1227506851?profile=RESIZE_1024x1024"></p>
The diagram could be improved here - this image at the moment is saying everything about the model - which I assume is not the overview scope - for an overview - you can stick to only the triangle with 5 steps. So that the model is focused - at the moment there is a lot of info in the image - due to the which i couldn't realize what is more important - how to work with it - or the model itself.

2020-08-26 13:14 UTC, udeysingh95 commented on 7-scrum-master-role/4-team-building.md
> +## What is Team?
Top half-titles are in question format - below half are not. Let's stick to one format. 
No questions in titles - as we did in the last PR as well and all others. If other, already opened PRs have questions in their titles as well - please make the improvements there as well - I won't comment this there then.

2020-08-27 16:53 UTC, udeysingh95 approved these changes

2020-08-27 17:06 UTC, Vaibhavpratapsingh22 requested changes

2020-08-27 17:06 UTC, Vaibhavpratapsingh22 commented on 7-scrum-master-role/4-team-building.md
> +**2. Enthusiasm and motivation of those involved:** Let everyone in the meeting know you appreciate their presence and you are grateful to have them on board and look forward to working together on t
```suggestion
**2. Enthusiasm and motivation of those involved:** Let everyone in the meeting know you appreciate their presence and you are grateful to have them on board and look forward to working together on the project. This makes people feel like they are important and sets a tone of professionalism and courtesy.\
```

2020-08-28 09:54 UTC, Vaibhavpratapsingh22 approved these changes

2020-08-28 10:35 UTC, merged