Create CODE_OF_CONDUCT.md
Vaibhavpratapsingh22/Courses pull request #55
Opened 2020-08-26 05:01 UTC by Vaibhavpratapsingh22

2020-08-26 06:41 UTC, udeysingh95 requested changes
Make it crisp. This is too long.

2020-08-26 10:20 UTC, SaarthakDeshmukh approved these changes
I see the said changes are been made. Good to go from my side. :white_check_mark:

2020-08-26 13:03 UTC, udeysingh95 requested changes
There are too many topics in this file at the moment - Think of what we actually practise - and somethings maybe -which we want to have in coming days or weeks. 
And keep only those. I think 10-20 lines should be more than enough to cover all that. 
At the moment - it is very detailed but its not ours and has too much irrelevant info.

2020-08-28 09:03 UTC, SaarthakDeshmukh reviewed
It's crisp and clear. For now, this is okay, but later on, when there are more people we need to add a few more specific details, like what kind of behavior is not tolerated. For ex. Changing someone else's file or structure of the files. and things like that.

2020-08-28 09:08 UTC, Vaibhavpratapsingh22 commented
> It's crisp and clear. For now, this is okay, but later on, when there are more people we need to add a few more specific details, like what kind of behavior is not tolerated. For ex. Changing someone else's file or structure of the files. and things like that.  

True @SaarthakDeshmukh i will update it time to time.

2020-08-28 15:25 UTC, udeysingh95 commented
It could be also added - new contributors are only allowed to "watch" in the beginning and commit nearly nothing. Also, maybe something around our whatsapp group. what do you say?
The language of this document is very official - and that is not the style of our work, nor team.

2020-08-28 16:02 UTC, Vaibhavpratapsingh22 commented
Okay, @udeysingh95 I will work on it.

2020-08-28 18:13 UTC, SaarthakDeshmukh commented on CODE_OF_CONDUCT.md
```suggestion
A code of conduct is a set of rules outlining the norms, rules, and responsibilities or proper practices of an individual party or an organization.
```

2020-08-29 05:58 UTC, udeysingh95 requested changes

2020-08-29 05:58 UTC, udeysingh95 commented on CODE_OF_CONDUCT.md
> +For any kind of support, complaint and query mail us at vaibhavpratapsingh22@gmail.com.
```suggestion
```

2020-08-29 06:07 UTC, udeysingh95 approved these changes

2020-08-29 06:14 UTC, merged