Advance Management Of Data
Vaibhavpratapsingh22/Courses pull request #57
Opened 2020-08-26 08:27 UTC by Vaibhavpratapsingh22

Chapter - 8 completed 👍

2020-08-26 13:43 UTC, udeysingh95 reviewed
Very nice work.

2020-08-26 13:43 UTC, udeysingh95 commented on 5-dbms/8-advance-management.md
> +A distributed database is basically a database that is not limited to one system, it is spread over different sites, i.e, on multiple computers or over a network of computers. A distributed database
Nothing to be added here - Just one question out of curiosity - could you think of some DDBMS around you in your daily life?

2020-08-26 13:43 UTC, udeysingh95 commented on 5-dbms/8-advance-management.md
> +2. **Horizontal scaling**: Horizontal scaling sometimes referred to as scaling out, is the process of adding more hardware to a system. This typically means adding nodes (new servers) to an existing
Can we do both at the same time? 
When do we need to scale up or scale-out? 
Is there something like scaling down as well - how is that approached? 
What happens to the company which is losing all of its customers and has a big database storage standing behind their walls?

2020-08-26 13:43 UTC, udeysingh95 commented on 5-dbms/8-advance-management.md
> +A network partition refers to network decomposition into relatively independent subnets for their separate optimization as well as network split due to the failure of network devices. In both cases t
how is it different from scaling out? or backing up?

2020-08-26 13:43 UTC, udeysingh95 commented on 5-dbms/8-advance-management.md
> +1. **Vertical Fragmentation**: In vertical fragmentation, the fields or columns of a table are grouped into fragments. In order to maintain re-constructiveness, each fragment should contain the prima
How is this decided that site 1 will have only names and nothing else? and what happens if site 1 needs second and third column information as well - doesn't it create just extra overhead to send requests to multiple sites?

2020-08-26 13:43 UTC, udeysingh95 commented on 5-dbms/8-advance-management.md
> +**3. Hybrid Fragmentation**: In hybrid fragmentation, a combination of horizontal and vertical fragmentation techniques are used. This is the most flexible fragmentation technique since it generates
Why there was a need to hybrid fragmentation? wasn't vertical and horizontal enough? what were they lacking in first place?

2020-08-26 13:43 UTC, udeysingh95 commented on 5-dbms/8-advance-management.md
> +**2. Horizontal Fragmentation**: Horizontal fragmentation groups the tuples of a table in accordance to values of one or more fields. Horizontal fragmentation should also confirm to the rule of recon
What if a new entry is needed to be created at site 1 - and the constraint on database is that email id must be unique for all the users? would the processor then run through all the sites and all the DBs and all the entries there?  Wouldnt that be just too much overhead and extra information processing!?

2020-08-26 13:43 UTC, udeysingh95 commented on 5-dbms/8-advance-management.md
> +5. Improved Performance: We can achieve inter-query and intr-query parallelism by executing multiple queries at different sites by breaking up a query into a number of sub-queries that basically exec
Are there any disadvantages as well?

2020-08-26 13:43 UTC, udeysingh95 commented on 5-dbms/8-advance-management.md
> +### 4. Graph-Based
Very well described!

2020-08-26 13:43 UTC, udeysingh95 commented on 5-dbms/README.md
> +We will learn about AMD which includes Distributed Data Management System(DDBMS) and NoSQL.
The chapter could be summarized in a better way here - this is too cold. It sounds like - you didn't like this chapter.

2020-08-27 12:51 UTC, Vaibhavpratapsingh22 commented on 5-dbms/8-advance-management.md
> +A distributed database is basically a database that is not limited to one system, it is spread over different sites, i.e, on multiple computers or over a network of computers. A distributed database
Yes, let us suppose there is a distributor of let's say aqua-guard. Then the distributor has n number of retailers. All the retailers have there own database(stock) and in case they get out of stock they directly tell the distributor and distributor gives them the stock. In case the distributor does not have stock he can arrange it from any other retailer. So like this, the distributor acts like a computer network and the retailers acts as sites.

2020-08-27 12:54 UTC, Vaibhavpratapsingh22 commented on 5-dbms/8-advance-management.md
> +2. **Horizontal scaling**: Horizontal scaling sometimes referred to as scaling out, is the process of adding more hardware to a system. This typically means adding nodes (new servers) to an existing
Should I add the answers in the chapter or here only or at both places.

2020-08-27 13:27 UTC, Vaibhavpratapsingh22 commented on 5-dbms/8-advance-management.md
> +2. **Horizontal scaling**: Horizontal scaling sometimes referred to as scaling out, is the process of adding more hardware to a system. This typically means adding nodes (new servers) to an existing
YES 
We need scale-up if our product is new and we are taking a chance to check if we increase the efficiency will there be more customer request for the product.
We need scale-out if we have a big company and lots of money. As scale-out means adding more machines. So we need manpower also.
I don't know about scaling down.
Company has many options as it has the user DATABASE
1. The company can check which product the max customers love and can launch the product with new features.
2. The company can send emails, SMS to the customers so that they feel connected to the company.
3. Happy customers equal good business so the company can focus on them and provide them with good offers and discounts.
and so on...

2020-08-27 13:53 UTC, Vaibhavpratapsingh22 commented on 5-dbms/8-advance-management.md
> +A network partition refers to network decomposition into relatively independent subnets for their separate optimization as well as network split due to the failure of network devices. In both cases t
In scaling-out, we add more machines to increase efficiency. Whereas in network partitioning we divide the nodes into different sections. So that we can have an easy check on there working, which is a better option than checking a complete scale-out.

2020-08-27 14:20 UTC, Vaibhavpratapsingh22 commented on 5-dbms/8-advance-management.md
> +1. **Vertical Fragmentation**: In vertical fragmentation, the fields or columns of a table are grouped into fragments. In order to maintain re-constructiveness, each fragment should contain the prima
This is just a simple example. 
Yeah that's true that if site 1 needs second and third column information it will create more efforts. But that is what it is made for means if site1 contains only names that mean there must be a huge demand of names only. So for that, we have made a separate site for name for the ease of the user.

2020-08-27 14:42 UTC, Vaibhavpratapsingh22 commented on 5-dbms/8-advance-management.md
> +**3. Hybrid Fragmentation**: In hybrid fragmentation, a combination of horizontal and vertical fragmentation techniques are used. This is the most flexible fragmentation technique since it generates
In vertical fragmentation, we display the selected columns whereas, in horizontal, we display the selected rows of the table. Whereas in hybrid fragmentation we can combine both horizontal and vertical together. 
Hybrid fragmentation comes in the game when we need more detailed data.

2020-08-27 15:07 UTC, Vaibhavpratapsingh22 commented on 5-dbms/8-advance-management.md
> +5. Improved Performance: We can achieve inter-query and intr-query parallelism by executing multiple queries at different sites by breaking up a query into a number of sub-queries that basically exec
YES 
1. If the number of sites increases it gets difficult to connect all the sites with one another.
2. Data security reduces as we are not able to check all the sites regularly.
3. Maintaining a proper standard i.e when the number of sites gets increased then it becomes very difficult to maintain the standard.

2020-08-27 15:16 UTC, Vaibhavpratapsingh22 commented on 5-dbms/8-advance-management.md
> +**2. Horizontal Fragmentation**: Horizontal fragmentation groups the tuples of a table in accordance to values of one or more fields. Horizontal fragmentation should also confirm to the rule of recon
There is no need to run through all the sites and all the DBs, we will just update the DB of site1. If in future we see that the site2 is demanding the same data repeatedly that we updated on site1. Then there we have 2 options;
1.  Either we always redirect site2 to site1 if the user wants the email-id data.
2. Or we copy the data from site1 in the DB of site2.

2020-08-27 16:53 UTC, udeysingh95 approved these changes

2020-08-28 08:32 UTC, SaarthakDeshmukh commented on 5-dbms/8-advance-management.md
> +A distributed database is basically a database that is not limited to one system, it is spread over different sites, i.e, on multiple computers or over a network of computers. A distributed database
Very nice example. @Vaibhavpratapsingh22 Keep it up.

2020-08-28 08:54 UTC, SaarthakDeshmukh commented on 5-dbms/8-advance-management.md
> +<p align="center"><img src="https://bitpanda-academy.imgix.net/nulld4cb2f71-953b-4308-8edc-63408bc35a1b/bitpanda-academy-intermediate-15-scaling-infographic.png?auto=compress%2Cformat&fit=min&fm=jpg&
Nice and simple Image. Good work there! I have one suggestion here, can we reduce the size a bit because the image has very little information to show but it's taking a lot of space.

2020-08-28 08:54 UTC, SaarthakDeshmukh commented on 5-dbms/8-advance-management.md
> +## Types of NoSQL Systems
I really liked this section It was very easy to read and I was connected to it the whole time.

2020-08-28 08:54 UTC, SaarthakDeshmukh commented on 5-dbms/8-advance-management.md
> +The chapter contains Distributed Database Management System(DDBMS), advantaged of DDBMS, NoSQL databases and types of NoSQL systems .
Here, Summary could be improved, right now it looks like README.md file summary

2020-08-28 15:02 UTC, SaarthakDeshmukh requested changes
Images are looking much better. Great work! Change the summary - there were some grammatical mistakes.

2020-08-28 15:02 UTC, SaarthakDeshmukh commented on 5-dbms/8-advance-management.md
> +So at the end, we now about DDBMS i.e distributed database management system, its types and advantages. Then we learned about fragmentation, its types.Moving on we discussed network partitioning and
```suggestion
So now we know all 

So in the end, now we know what is DDBMS, Fragmentation, its types, and its advantages. We also discussed network partitioning and partition tolerance, and Lastly, we learned about NoSQL, its types with some examples.
```

2020-08-28 15:05 UTC, SaarthakDeshmukh approved these changes
Good to go!

2020-08-28 15:07 UTC, merged