Chapter 5 - Moderation
Vaibhavpratapsingh22/Courses pull request #58
Opened 2020-08-26 12:39 UTC by SaarthakDeshmukh

Chapter 5 completed successfully.  :tada: :white_check_mark

2020-08-26 13:21 UTC, udeysingh95 requested changes
Good size of the file.
As I mentioned earlier as well, a coach or a SM should have good communication and teaching skills because its one of their regular instance.  They should be skilled/proficient in giving their message in the easiest way possible. I see this lacking a bit in these PRs. 
Theres nothing to worry about it - keep practising and you will improve it. We are all here to learn only. 
Its your sandbox to try and fail and learn - remember- fail fast and learn. ;)

2020-08-26 13:21 UTC, udeysingh95 commented on 7-scrum-master-role/5-moderation.md
> +Moderation is unconventionally regarded as a means of conducting meetings or group activities in a non-controlling manner. It aims at making use of group knowledge by involving group members in the d
Very scientific way of explaining moderation - how would you describe it to a 6 year old kid? Use that language.

2020-08-26 13:21 UTC, udeysingh95 commented on 7-scrum-master-role/5-moderation.md
> +## Scrum Master as Moderator
This is the heart of this chapter - and it comes almost at the end. 
Try to start with this and keep the knowledge revolving around SM as moderator. 
If you prefer to moderator as the core of this chapter and then quickly connect with SM role - as it is now - then that is fine as well - just give a justification for that - why did you choose to go that way? 
i would be interested to hear your thoughts then.

2020-08-26 13:21 UTC, udeysingh95 commented on 7-scrum-master-role/5-moderation.md
> +The 7 most important qualities of a great moderator.
Points start right after the title. There is only a cover-up standing here - which is clear. Try to use para format to open up a section.

2020-08-26 13:21 UTC, udeysingh95 commented on 7-scrum-master-role/5-moderation.md
> +1. Natural curiosity: Phrases like “I don’t know,” “I guess so” and “I’m not sure” create great opportunities to any true moderator. No accomplished moderator will allow any of these responses to be
Flat information - how can we make it more engaging? I like the points given below - but Its hard to go in each and read them.

2020-08-27 10:09 UTC, udeysingh95 approved these changes

2020-08-27 10:09 UTC, udeysingh95 commented on 7-scrum-master-role/5-moderation.md
> +A Moderator is someone who tries to help other people come to an agreement. They help the meeting group to achieve its goals in a focused manner. To guide the discussion in the proper direction, focu
Very interesting question - how is a moderator different from a facilitator?

2020-08-27 11:29 UTC, Vaibhavpratapsingh22 approved these changes

2020-08-27 12:26 UTC, SaarthakDeshmukh commented on 7-scrum-master-role/5-moderation.md
> +A Moderator is someone who tries to help other people come to an agreement. They help the meeting group to achieve its goals in a focused manner. To guide the discussion in the proper direction, focu
We can say a Facilitator is a person responsible for promoting a Process and a Moderator is more of a guide, helps the team to achieve its goals in a focused manner. For ex, SM acts as a facilitator in Sprint Retrospective and moderator in review and other ceremonies, What are your views? @udeysingh95

2020-08-27 13:04 UTC, Vaibhavpratapsingh22 requested changes

2020-08-27 13:04 UTC, Vaibhavpratapsingh22 commented on 7-scrum-master-role/5-moderation.md
> +### 1. Natural curiosity:
Remove the colons ":" from all the headings.

2020-08-27 13:04 UTC, Vaibhavpratapsingh22 commented on 7-scrum-master-role/5-moderation.md
> +## Scrum Master as Moderator
Can we add one or two images as there is no image in the whole chapter which looks very boring to me. I would like to see some images. What u say??

2020-08-27 16:54 UTC, udeysingh95 commented on 7-scrum-master-role/5-moderation.md
> +A Moderator is someone who tries to help other people come to an agreement. They help the meeting group to achieve its goals in a focused manner. To guide the discussion in the proper direction, focu
sounds fair!

2020-08-27 16:57 UTC, udeysingh95 commented on 7-scrum-master-role/5-moderation.md
> +## Scrum Master as Moderator
Maybe 1 is ok. Chapter content itself is amusing. Did you get a chance to read the content once @Vaibhavpratapsingh22 ?

2020-08-27 17:05 UTC, Vaibhavpratapsingh22 commented on 7-scrum-master-role/5-moderation.md
> +## Scrum Master as Moderator
Yes

2020-08-28 09:44 UTC, SaarthakDeshmukh commented on 7-scrum-master-role/5-moderation.md
> +## Scrum Master as Moderator
@Vaibhavpratapsingh22 I tried finding an image, but none of them are giving an impact. So can we let this chapter be without an image? as it is a very small chapter. What are your views?

2020-08-28 09:47 UTC, Vaibhavpratapsingh22 commented on 7-scrum-master-role/5-moderation.md
> +## Scrum Master as Moderator
Yeah, no problem.

2020-08-28 09:52 UTC, Vaibhavpratapsingh22 approved these changes

2020-08-28 10:38 UTC, merged