Chapter 6 - Teaching
Vaibhavpratapsingh22/Courses pull request #61
Opened 2020-08-29 17:03 UTC by SaarthakDeshmukh

Completed chapter no. 6 successfully.

2020-08-29 17:29 UTC, Vaibhavpratapsingh22 commented
## Fantastic Work 🚀

2020-08-29 17:31 UTC, Vaibhavpratapsingh22 commented on 7-scrum-master-role/6-teaching.md
> +And here is a link where you can download the ([Template](https://user-images.githubusercontent.com/63605352/91640468-16c2b900-ea1e-11ea-985e-1b375def798d.png)).\
```suggestion
And here is a link where you can download the ([Template](https://user-images.githubusercontent.com/63605352/91640468-16c2b900-ea1e-11ea-985e-1b375def798d.png)).
```

2020-08-29 17:32 UTC, Vaibhavpratapsingh22 commented on 7-scrum-master-role/6-teaching.md
> +I have also attached the PDF of the book, where you can find more information about this framework.
```suggestion
I have also attached the PDF of the book, where you can find more information about this framework.\
```

2020-08-29 17:35 UTC, Vaibhavpratapsingh22 requested changes

2020-08-29 17:35 UTC, Vaibhavpratapsingh22 commented on 7-scrum-master-role/6-teaching.md
> +
Can we somehow reduce these points or present it in a more beautiful way, because as of now it looks very lengthy

2020-08-30 10:01 UTC, SaarthakDeshmukh commented on 7-scrum-master-role/6-teaching.md
> +
I will try to change it.

2020-08-30 16:28 UTC, udeysingh95 approved these changes

2020-08-30 18:50 UTC, SaarthakDeshmukh commented on 7-scrum-master-role/6-teaching.md
> +
I have updated the file. @Vaibhavpratapsingh22 check it out.

2020-08-31 04:41 UTC, Vaibhavpratapsingh22 approved these changes

2020-08-31 16:20 UTC, merged