Dbms mongo 3
Vaibhavpratapsingh22/Courses pull request #63
Opened 2020-08-30 08:35 UTC by Vaibhavpratapsingh22

Chapter - 3 created 🏎️

2020-08-30 16:01 UTC, udeysingh95 requested changes
Overall great work. 
There is some issue with the use of "quote" style formatting where "code" style formatting is expected. After that improvement - it looks good to go from my side. 
I would appreciate your review here @giteshk11. 
and @Dhillon-in your review for the completeness and the understandability of code - as you were looking forward to learning it. 
You can read and answer a simple question - was it helpful for you to learn about MongoDB collections or not?

2020-08-30 16:08 UTC, SaarthakDeshmukh commented on 5-dbms/9-mongodb/3-collections.md
> +<img src="https://user-images.githubusercontent.com/54719422/91654231-c3f00c80-eac4-11ea-9c48-582d2fcee2e2.png " height="" width="">
For me, it's loading properly.

2020-08-30 16:16 UTC, Vaibhavpratapsingh22 commented on 5-dbms/9-mongodb/3-collections.md
> +<img src="https://user-images.githubusercontent.com/54719422/91654231-c3f00c80-eac4-11ea-9c48-582d2fcee2e2.png " height="" width="">
I will upload it once more.

2020-08-30 16:30 UTC, udeysingh95 approved these changes

2020-08-30 16:30 UTC, udeysingh95 commented
Let's wait for other reviews here.

2020-09-01 07:22 UTC, SaarthakDeshmukh requested changes
Overall the readability of the PR was not at an issue. Great Work there! just a few structural changes.

2020-09-01 07:24 UTC, SaarthakDeshmukh commented on 5-dbms/9-mongodb/3-collections.md
> +**Syntax**:\
The description is not in line and below it is in the line. Try to follow one structure.

2020-09-01 07:25 UTC, SaarthakDeshmukh commented on 5-dbms/9-mongodb/3-collections.md
> +<img src="https://user-images.githubusercontent.com/54719422/91653771-28a96800-eac1-11ea-9056-efe10f48190a.png" height="" width="">
Images can be placed at the center. It would look nice.

2020-09-01 07:25 UTC, SaarthakDeshmukh commented on 5-dbms/9-mongodb/3-collections.md
> +**Note**:Your created database (shopdb) is not present in list. To display database, you need to insert at least one document into it.
```suggestion
**Note**: Your created database (shopdb) is not present in the list. To display a database, you need to insert at least one document into it.
```

2020-09-01 09:00 UTC, SaarthakDeshmukh approved these changes

2020-09-01 09:15 UTC, merged