Chapter 7 - Coaching
Vaibhavpratapsingh22/Courses pull request #64
Opened 2020-08-30 16:41 UTC by SaarthakDeshmukh

Completed the coaching chapter successfully.

2020-08-30 16:54 UTC, Vaibhavpratapsingh22 requested changes
## Great Work 🏎️ 
Some minor changes from my side.

2020-08-30 16:54 UTC, Vaibhavpratapsingh22 commented on 7-scrum-master-role/7-coaching.md
> +## Scrum Master Coaches
I think this should be at level 3.

2020-08-30 16:54 UTC, Vaibhavpratapsingh22 commented on 7-scrum-master-role/7-coaching.md
> +1. _Consulting_ - A consultant provides expertise and solves business problems, or develops a business as a whole.
can we use "**" here for the points?

2020-08-30 16:54 UTC, Vaibhavpratapsingh22 commented on 7-scrum-master-role/7-coaching.md
> +3. _Teaching_ - is passing on information or skill to help others learn new things.
change "-" to ":"

2020-08-30 17:14 UTC, udeysingh95 requested changes
I agree with the points from Vaibhav - also some things can be added from content point of view. More coaching models and links to them will be helpful as well. 
Some coaching topics - some cases - where coaching is needed but not clearly visible. When do you as an SM coaches a team or an individual - this is very difficult to identify in actual practice. 
Do they come to you or you go to them? what do you talk about? 
How do you act as a coach only and not jump into a consultant or a mentor in that session - as people generally come to you - seeking direct solutions.

2020-08-30 17:14 UTC, udeysingh95 commented on 7-scrum-master-role/7-coaching.md
> +Coaching empowers and brings out the best in them. SM as a coach helps in unleashing a person’s or a team’s latent potential. This helps to maximize performance with the same amount of effort. It's a
I think GROW model is very important and deserves its own section. What are some other coaching frameworks? Maybe quickly describe like 4 or 5 or them here.

2020-08-30 17:14 UTC, udeysingh95 commented on 7-scrum-master-role/7-coaching.md
> +**3. Powerful Questioning:** The SM uses powerful questions to fuel coaching conversations. SM learns and practices this art of asking questions. What makes a powerful question?\
why there is no space before starting here?

2020-08-30 17:14 UTC, udeysingh95 commented on 7-scrum-master-role/7-coaching.md
> +**4. Leading by Example:** To be able to earn trust and influence others, the SM must exhibit behaviors that she so desires from her coachees. A good coach has a learning attitude, welcomes feedback,
And here is space - and also one empty space before "4." is rendered.

2020-08-30 17:17 UTC, udeysingh95 commented
The following sections: 
5. Active Listening model
6. Powerful questions
7. Art of asking Powerful questions?

Have been given their own importance but in the PR - they have been discussed as the lowest part - making it okish important for coaching. 
I didn't see any deep content on asking powerful questions, nor Active listening. If you are running out of space - link the references after explaining them shortly. 
As of now - it contains very theoretical knowledge and the real touch of coaching and its tools and its challenges are missing from this PR.

2020-08-30 19:05 UTC, SaarthakDeshmukh commented on 7-scrum-master-role/7-coaching.md
> +**4. Leading by Example:** To be able to earn trust and influence others, the SM must exhibit behaviors that she so desires from her coachees. A good coach has a learning attitude, welcomes feedback,
There are no extra spacing rendering in mine 🤔

2020-08-30 19:34 UTC, SaarthakDeshmukh commented on 7-scrum-master-role/7-coaching.md
> +**3. Powerful Questioning:** The SM uses powerful questions to fuel coaching conversations. SM learns and practices this art of asking questions. What makes a powerful question?\
I have given equal spaces, but still, I will check it once.

2020-08-31 12:24 UTC, udeysingh95 requested changes
Cover two more frameworks - 
SBI & 5D 
5D is very effective for team coaching and you can read more about it in The HH Guide by Agile42.

2020-08-31 12:24 UTC, udeysingh95 commented on 7-scrum-master-role/7-coaching.md
> +**1. GROW MODEL:**
Title after title.

2020-08-31 12:24 UTC, udeysingh95 commented on 7-scrum-master-role/7-coaching.md
> +To read more on this model click [here](https://www.mindtools.com/pages/article/newLDR_89.htm).\
Also, there is no words for this model here - at least a small quick para to give an overview to the framework and then if reader finds in interesting - they can click on link and go and read more. In the current state, they will click her for sure and will never come back.

2020-08-31 12:24 UTC, udeysingh95 commented on 7-scrum-master-role/7-coaching.md
> +<p align="center"> <img width="600" height="" src="https://user-images.githubusercontent.com/63605352/91661313-94003380-eadb-11ea-8c95-04370d5179bd.JPG"></p>
Image right after the title

2020-08-31 12:24 UTC, udeysingh95 commented on 7-scrum-master-role/7-coaching.md
> +**2. Powerful Questioning:** The SM uses powerful questions to fuel coaching conversations. SM learns and practices this art of asking questions. What makes a powerful question?\
![Screenshot 2020-08-31 at 17 48 51](https://user-images.githubusercontent.com/15111643/91719074-47d3f280-ebb2-11ea-9b5a-45c858954001.png)
This is how it is rendered. The link is breaking the line badly. There is a weird space in the beginning for 2 lines.

2020-08-31 12:24 UTC, udeysingh95 commented on 7-scrum-master-role/7-coaching.md
> +**2. Powerful Questioning:** The SM uses powerful questions to fuel coaching conversations. SM learns and practices this art of asking questions. What makes a powerful question?\
Image in powerful question section is good. I liked it

2020-08-31 12:24 UTC, udeysingh95 commented on 7-scrum-master-role/7-coaching.md
> +**Art of Powerful Questions:** There is a great quote by Albert Einstein - “If I had an hour to solve a problem and my life depended on the solution, I would spend the first 55 minutes determining th
What happened to the numbers here?

2020-08-31 12:24 UTC, udeysingh95 commented on 7-scrum-master-role/7-coaching.md
> +Coaching is one of the essential skills required for a Scrum Master to be effective. Here we say what is coaching and What is 'NOT'. Along with that, we saw skills which are important for SM to be a
I didnt the meaning of last line:

> To read more on what are the different types of coach SM is

And wouldn't it be a good idea - to redirect the reader to your own folder on this repo - because i assume that aspiring SM can learn it all there - or no?

2020-08-31 12:41 UTC, SaarthakDeshmukh commented on 7-scrum-master-role/7-coaching.md
> +Coaching is one of the essential skills required for a Scrum Master to be effective. Here we say what is coaching and What is 'NOT'. Along with that, we saw skills which are important for SM to be a
This was just for explaining different types of coaches, it's irrelevant, I will remove that line.

2020-08-31 12:42 UTC, SaarthakDeshmukh commented on 7-scrum-master-role/7-coaching.md
> +**Art of Powerful Questions:** There is a great quote by Albert Einstein - “If I had an hour to solve a problem and my life depended on the solution, I would spend the first 55 minutes determining th
I'll add them, I thought as it is dealing with the same topic I did not give an extra number.

2020-08-31 12:43 UTC, SaarthakDeshmukh commented on 7-scrum-master-role/7-coaching.md
> +<p align="center"> <img width="600" height="" src="https://user-images.githubusercontent.com/63605352/91661313-94003380-eadb-11ea-8c95-04370d5179bd.JPG"></p>
I will add a para

2020-08-31 12:56 UTC, SaarthakDeshmukh commented
I totally forgot about the 5D model. Thanks for reminding me.🤗 @udeysingh95

2020-09-01 05:14 UTC, Vaibhavpratapsingh22 approved these changes

2020-09-01 08:58 UTC, udeysingh95 approved these changes

2020-09-01 09:06 UTC, merged