Dbms mongo 4
Vaibhavpratapsingh22/Courses pull request #65
Opened 2020-08-31 10:38 UTC by Vaibhavpratapsingh22

Chapter-4 created 🦅 
CRUD OPERATIONS

2020-08-31 12:06 UTC, udeysingh95 requested changes
There is a whole separate section of practical - I think it would be nice to have it in the theory only. Like when you described them - add the practical screen with some words there only. So its all relevant. Having it all in the end - is like scrolling up and down again and again - to check what was written above and what is it saying here below. 
Also, the readability is pretty low in this PR, somewhere there are numbers, in some places there are not. I also couldn't follow - what is parent and what is child + each section has its body style - which makes it hard to follow till the end. 

Also, README update is missing.

2020-08-31 12:06 UTC, udeysingh95 commented on 5-dbms/9-mongodb/4-crud-operations.md
> +### Syntax and Example with command
This is third level without number

2020-08-31 12:06 UTC, udeysingh95 commented on 5-dbms/9-mongodb/4-crud-operations.md
> +### 1. findOneAndUpdate() method
This is third level with number. I didn't get - if this is a separate section within the same section or is it a part of "Syntax and example command"

2020-08-31 12:53 UTC, Vaibhavpratapsingh22 commented
@udeysingh95, I think we should update the README.md at the last.
What u say??

2020-08-31 14:42 UTC, udeysingh95 reviewed
Cool work!

2020-08-31 14:42 UTC, udeysingh95 commented on 5-dbms/9-mongodb/4-crud-operations.md
> +**Description**: In the below image we first set the database to employeedb. Then we see that there is collection named emp_details. So we insertOne  document in the collection and then insertMany do
As description term is self-understood here and acting only as a brain pillar.

2020-08-31 14:42 UTC, udeysingh95 commented on 5-dbms/9-mongodb/4-crud-operations.md
> +### Practical
This is nice to make it explicit but this practical implementation is expected to be done in this PR - so lets leave out the title.

2020-09-01 07:31 UTC, SaarthakDeshmukh approved these changes
The PR is looking perfect. No change from my side. Good Work @Vaibhavpratapsingh22 :rocket:

2020-09-01 08:59 UTC, udeysingh95 requested changes

2020-09-01 08:59 UTC, udeysingh95 commented on 5-dbms/9-mongodb/4-crud-operations.md
> +## Update Operations
```suggestion
## 3. Update Operations
```

2020-09-01 08:59 UTC, udeysingh95 commented on 5-dbms/9-mongodb/4-crud-operations.md
> +## Delete Operations
```suggestion
## 4. Delete Operations
```

2020-09-01 09:03 UTC, udeysingh95 approved these changes

2020-09-01 09:15 UTC, merged