Cn ip addressing
Vaibhavpratapsingh22/Courses pull request #84
Opened 2020-09-18 13:26 UTC by Vaibhavpratapsingh22

Chapter - 8 created 👍 
I enjoyed making the content of the chapter very interesting topics.

2020-09-19 13:43 UTC, udeysingh95 requested changes
README is good updated. 
Some improvements: 
- [x] Add network images as well 
- [x] Line limit has crossed.

2020-09-19 13:43 UTC, udeysingh95 commented on 6-computer-networks/8-ip-addressing.md
> +<p text align="center"><img src="https://user-images.githubusercontent.com/54719422/93597818-4d667080-f9d9-11ea-8a3a-0ac28832a22a.png"></p>
I would like to see the network as well in a screen shot.

2020-09-19 14:48 UTC, Vaibhavpratapsingh22 commented
![Screenshot (105)](https://user-images.githubusercontent.com/54719422/93669970-35fcb580-fab5-11ea-9e92-7d87e2c5d407.png)

2020-09-20 07:07 UTC, udeysingh95 commented
Network image is still missing. 
Screenshot of packet tracer 
Showing the setup of the network. You can also make vlans in it using red circles 
And mentioning their names as labels

2020-09-20 07:37 UTC, Vaibhavpratapsingh22 commented
OK @udeysingh95, I will add the image in the md file.
Yes, we can make multiple VLAN's using a single switch.

2020-09-20 11:59 UTC, udeysingh95 approved these changes

2020-09-21 08:24 UTC, merged