Linkedin profile
Vaibhavpratapsingh22/Courses pull request #96
Opened 2020-09-30 06:26 UTC by Vaibhavpratapsingh22

Chapter-1 👍

2020-10-03 07:52 UTC, udeysingh95 requested changes
This is a special chapter - feel free to write it as long as you need and want. I see a big deficiency of content on this PR - this PR is only talking about what is section "x" and what is section "y"! This isn't the purpose of this PR. 
The purpose is to learn how to create and put nice, attractive, professional content in those sections and what are the good practises.

2020-10-03 07:52 UTC, udeysingh95 commented on 11-linkedin/1-profile.md
> +##  Picture And Cover
this topic suddenly comes from nowhere - correct and connect the flow of content in this chapter.

2020-10-03 07:52 UTC, udeysingh95 commented on 11-linkedin/1-profile.md
> +<p text align="center"></p><img src="https://www.thebalancecareers.com/thmb/EptDIw2uysv-KHddKl0poWA6q7Q=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/take-a-professional-pho
this image says the same things - as written above in the text. 
Better way of using image would be to show - what are examples of bad pictures and good pictures for linkedin - both cover and profile.

2020-10-03 07:52 UTC, udeysingh95 commented on 11-linkedin/1-profile.md
> +##  Headline
This topic - is quite important and it plays an important role in SEO of your profile. 
you didn't mention that at all. Also - some examples are recommended to add in each section - as the theory part is known to everyone - but how it looks like in the end - is a big question mark to all.

2020-10-03 07:52 UTC, udeysingh95 commented on 11-linkedin/1-profile.md
> +## Summary
update the content - there is no more linking available in the summary section. its only text. Also, there are no tips to write summary anywhere - everyone knows already - what summary is! and that is what you have written again. 
maybe show some good and bad summaries also - if you can design a template - use that.

2020-10-03 07:52 UTC, udeysingh95 commented on 11-linkedin/1-profile.md
> +## Summary
We dont want to learn here - what and where to write summary in linkedin profile - we want to learn - how to write an eye catching summary on your linkedin profile. Change the whole content in this section as well.

2020-10-03 07:52 UTC, udeysingh95 commented
## Read more.

2020-10-03 07:53 UTC, udeysingh95 commented
also - topic-0 "url" is not mentioned

2020-10-04 14:18 UTC, SaarthakDeshmukh requested changes
Overall I could understand everything. This will help a lot of people as you are gathering all the relevant information in one place. Great Work @Vaibhavpratapsingh22

2020-10-04 14:18 UTC, SaarthakDeshmukh commented on 11-linkedin/README.md
> +LinkedIn, business-oriented social networking Web site founded in 2002 and headquartered in Mountain View, California. In 2016 LinkedIn was acquired by Microsoft for approximately $26 billion. The fo
```suggestion
LinkedIn, business-oriented social networking Web site founded in 2002 and headquartered in Mountain View, California. In 2016 LinkedIn was acquired by Microsoft for approximately $26 billion. The following year it reported more than 500 million members in about 200 countries. LinkedIn, business-oriented social networking Web site founded in 2002 and headquartered in Mountain View, California. Unlike other social networks such as Facebook, instagram which are often purely recreational, LinkedIn emphasizes a user’s professional connections. Users create profile pages that have a structure similar to a résumé, in that users can summarize their career, advertise their particular skills, and list their education and employment history. Connections are formed between users when one accepts an invitation from another to join his or her network. LinkedIn allows users to further their careers by searching for jobs, finding connections (even at third hand) at a particular company, and receiving recommendations from other users. 
```

2020-10-04 14:18 UTC, SaarthakDeshmukh commented on 11-linkedin/1-profile.md
> +## Summary
The image is looking nice. I can take some inspiration to write my LinkedIn summary.

2020-10-04 14:18 UTC, SaarthakDeshmukh commented on 11-linkedin/1-profile.md
> +## Adding Profile and Background Picture
This section is nicely explained.

2020-10-04 17:16 UTC, udeysingh95 approved these changes

2020-10-04 17:23 UTC, merged