Linkedin networking
Vaibhavpratapsingh22/Courses pull request #98
Opened 2020-10-01 17:27 UTC by Vaibhavpratapsingh22

Chapter -2 created 👍

2020-10-03 07:56 UTC, udeysingh95 requested changes
I like the direction and amount of content on this PR. But networking is one of the thing that really helps to excel on Linkedin. 
The content on the PR - is good but could be found very easily on internet in one search. I would like to read something which I haven't read so far - and I have read a lot of stuff about networking. 
I expect you to do deeper research. Current state of information is very naive. 

With deeper search on this topic - will really help you to gain a massive network on Linkedin. Massive means - 10,000+

2020-10-03 18:06 UTC, Vaibhavpratapsingh22 commented
@udeysingh95, I searched a lot on networking but everywhere I found the same tactics that I have already mentioned. Though, I have changed some content which I founded more relevant. So please check it 👍

2020-10-04 14:25 UTC, SaarthakDeshmukh commented on 11-linkedin/1-profile.md
> +
Why there is an extra spacing here and below in the next topic also?

2020-10-04 14:29 UTC, SaarthakDeshmukh requested changes
Networking can be done through campaigns also, Check some more links around that, It might be helpful. I liked the way you have summarized some topics in this PR. Good Job!

2020-10-04 14:29 UTC, SaarthakDeshmukh commented on 11-linkedin/2-networking.md
> +
Extra Spacing in between.

2020-10-04 14:29 UTC, SaarthakDeshmukh commented on 11-linkedin/2-networking.md
> +### 5. Become A Connector
There is space before every new heading and here there is no space.

2020-10-04 17:18 UTC, udeysingh95 commented
Networking is heavily done using #opennetworkers - this is a concept on Linkedin - there are a lot of people who are interested in networking to anyone - and these people often post for more networking - and you can connect to hundreds of people through one post only. Read and add to the content about it.

2020-10-05 20:06 UTC, udeysingh95 approved these changes

2020-10-06 08:57 UTC, SaarthakDeshmukh approved these changes

2020-10-06 09:07 UTC, merged