Linkedin recommendation
Vaibhavpratapsingh22/Courses pull request #99
Opened 2020-10-02 11:53 UTC by Vaibhavpratapsingh22

Chapter -3 created 👍

2020-10-03 08:01 UTC, udeysingh95 requested changes
I see - that you are trying to control the amount the lines which is reducing the amount and quality of content on PRs - lets set it free - no more line limits for this issue - i will update the issue as well accordingly. 

Good that you talked about what and how important it is! 
recommendation tips section is sounding like - how to write a recommendation - use an apt title there. 

then you have provided some templates - which is good - but they are too less - i would suggest to use screenshots here - as it would faster and easier for you also - you can also choose one specific direction of recommendations - like to write recommendation for frontend web developers. and also add a lot of nice resourceful links where we can go and read further about it. 
don't add just links - make sure they are of high quality. some resources are just there for nothing. 

One very important thing that you missed here is - its difficult to get recommendations on Linkedin - why behind it? and how to overcome that and have like 100s of recommendations?

2020-10-05 09:43 UTC, SaarthakDeshmukh requested changes
Great Work! Good to go. Just a small change

2020-10-05 09:43 UTC, SaarthakDeshmukh commented on 11-linkedin/3-recommendation.md
> +A recommendation is a statement that is written by a LinkedIn member to recognize or commend a connection, such as a colleague, business partner, or student. People who view your profile will often r
This can be merged to the previous line as it doesn't make sense to have an extra line.

2020-10-05 20:08 UTC, udeysingh95 approved these changes

2020-10-06 08:57 UTC, SaarthakDeshmukh approved these changes

2020-10-06 09:11 UTC, merged